#include "plugin.h"

ZATHURA_PLUGIN_REGISTER_WITH_FUNCTIONS("gdk-pixbuf", VERSION_MAJOR, VERSION_MINOR, VERSION_REV,
                                       ZATHURA_PLUGIN_FUNCTIONS({
                                           .document_open            = picture_open,
                                           .document_free            = picture_free,
                                           .document_index_generate  = picture_index_generate,
                                           .document_save_as         = picture_save_as,
                                           .document_attachments_get = picture_attachments_get,
                                           .document_attachment_save = picture_attachment_save,
                                           .document_get_information = picture_get_information,
                                           .page_init                = picture_init,
                                           .page_clear               = picture_clear,
                                           .page_search_text         = picture_search_text,
                                           .page_links_get           = picture_links_get,
                                           .page_form_fields_get     = picture_form_fields_get,
                                           .page_images_get          = picture_page_images_get,
                                           .page_get_text            = picture_get_text,
                                           .page_get_selection       = picture_get_selection,
                                           .page_render_cairo        = picture_page_render_cairo,
                                           // .page_image_get_cairo     = pdf_page_image_get_cairo,
                                           // .page_get_label           = pdf_page_get_label,
                                           // .page_get_signatures      = pdf_page_get_signatures,
                                       }),
                                       ZATHURA_PLUGIN_MIMETYPES({"image/png", "image/jpeg", "image/tiff", "image/tga",
                                                                 "image/gif"}))
