#include "plugin.h"

ZATHURA_PLUGIN_REGISTER_WITH_FUNCTIONS("gdk-pixbuf", VERSION_MAJOR, VERSION_MINOR, VERSION_REV,
                                       ZATHURA_PLUGIN_FUNCTIONS({
                                           .document_open            = image_open,
                                           .document_free            = image_free,
                                           .document_index_generate  = image_index_generate,
                                           .document_save_as         = image_save_as,
                                           .document_attachments_get = image_attachments_get,
                                           .document_attachment_save = image_attachment_save,
                                           .document_get_information = image_get_information,
                                           .page_init                = image_init,
                                           .page_clear               = image_clear,
                                           .page_search_text         = image_search_text,
                                           .page_links_get           = image_links_get,
                                           .page_form_fields_get     = image_form_fields_get,
                                           .page_images_get          = image_page_images_get,
                                           .page_get_text            = image_get_text,
                                           .page_get_selection       = image_get_selection,
                                           .page_render_cairo        = image_page_render_cairo,
                                           .page_image_get_cairo     = image_page_image_get_cairo,
                                           .page_get_label           = image_page_get_label,
                                           .page_get_signatures      = image_page_get_signatures,
                                       }),
                                       ZATHURA_PLUGIN_MIMETYPES({"image/png", "image/jpeg", "image/tiff", "image/tga",
                                                                 "image/gif"}))
